print("Welcome to the Love Calculator")
name1=input("What is your name?\n")
name2=input("What is their name?\n")
name3=name1.lower()
name4=name2.lower()
d1=int(name3.count("t"))
d2=int(name3.count("r"))
d3=int(name3.count("u"))
d4=int(name3.count("e"))
d5=int(name4.count("t"))
d6=int(name4.count("r"))
d7=int(name4.count("u"))
d8=int(name4.count("e"))
d=str(d1+d2+d3+d4+d5+d6+d7+d8)
e1=int(name3.count("l"))
e2=int(name3.count("o"))
e3=int(name3.count("v"))
e4=int(name3.count("e"))
e5=int(name4.count("l"))
e6=int(name4.count("o"))
e7=int(name4.count("v"))
e8=int(name4.count("e"))
e=str(e1+e2+e3+e4+e5+e6+e7+e8)
k=d+e
if int(k)>90 or int(k)<10:
    print("Your score is "+ k + ",you two together are like coke and mentos")
elif int(k)>40 and int(k)<50:
    print("Your score is "+ k + ",you two are alright together")
else:
    print("Your score is "+ k)